
services:
  db:
    container_name: pacients_sql
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: pacients_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db

  angular:
    container_name: pacients_angular
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./angular:/app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0 --poll 500"
    ports:
      - 4200:4200
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  php:
    container_name: pacients_php
    build: ./php
    ports:
      - 8000:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
